# Generated by Django 3.1.7 on 2022-03-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(max_length=20, verbose_name='JAN')),
                ('hinban', models.CharField(max_length=10, verbose_name='品番')),
                ('kataban', models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('7', '07')], max_length=10, verbose_name='型番')),
            ],
        ),
    ]
