# Generated by Django 3.1.7 on 2022-03-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='ブランド名')),
                ('hinban', models.CharField(max_length=20, verbose_name='品番')),
                ('hinmei', models.CharField(max_length=100, verbose_name='品名')),
                ('color_no', models.CharField(max_length=10, verbose_name='カラーNo')),
                ('color_name', models.CharField(max_length=40, verbose_name='カラー名')),
                ('size_no', models.CharField(max_length=10, verbose_name='サイズNo')),
                ('size_name', models.CharField(max_length=40, verbose_name='サイズ名')),
                ('jan', models.CharField(max_length=20, verbose_name='JAN')),
            ],
        ),
    ]
