# Generated by Django 3.1.7 on 2022-04-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_hinban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(max_length=20, verbose_name='JAN')),
                ('hinban', models.CharField(max_length=20, verbose_name='品番')),
            ],
        ),
        migrations.CreateModel(
            name='Trade_kyoten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('yubin', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('pref', models.CharField(max_length=4, verbose_name='都道府県')),
                ('address1', models.CharField(max_length=16, verbose_name='住所1')),
                ('address2', models.CharField(max_length=28, verbose_name='住所2')),
                ('company', models.CharField(blank=True, max_length=16, verbose_name='会社名')),
                ('sei', models.CharField(max_length=5, verbose_name='姓')),
                ('mei', models.CharField(blank=True, max_length=5, verbose_name='名')),
                ('tel', models.CharField(max_length=11, verbose_name='電話番号')),
                ('ninushi_name', models.CharField(max_length=20, verbose_name='荷主名')),
                ('ninushi_tel', models.CharField(max_length=11, verbose_name='荷主電話')),
            ],
        ),
    ]
