# Generated by Django 4.2.1 on 2026-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_trade_hinban_trade_kyoten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, verbose_name='ID')),
                ('hinban', models.CharField(max_length=255, verbose_name='品番')),
                ('color_name', models.CharField(max_length=255, verbose_name='カラー')),
                ('color_code', models.CharField(max_length=255, verbose_name='カラーコード')),
                ('size_name', models.CharField(max_length=255, verbose_name='サイズ')),
                ('size_code', models.CharField(max_length=255, verbose_name='サイズコード')),
            ],
        ),
    ]
